// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfeo3194iczUkOiXY6xl8iV6US7_pFg3k',
    appId: '1:832200775771:web:12a3df58aa98190515477e',
    messagingSenderId: '832200775771',
    projectId: 'icar-2d12c',
    authDomain: 'icar-2d12c.firebaseapp.com',
    storageBucket: 'icar-2d12c.firebasestorage.app',
    measurementId: 'G-4ZKRE93PP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqrIaRifHOC0bbMksZg4DNU0b4kYJ488E',
    appId: '1:832200775771:android:583814bf4d5bec3315477e',
    messagingSenderId: '832200775771',
    projectId: 'icar-2d12c',
    storageBucket: 'icar-2d12c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgH9dJMTcWGYGxl6Rs0CXPxnlADumLFO4',
    appId: '1:832200775771:ios:1b8ff48f5118379515477e',
    messagingSenderId: '832200775771',
    projectId: 'icar-2d12c',
    storageBucket: 'icar-2d12c.firebasestorage.app',
    iosBundleId: 'com.mycompany.icarusers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgH9dJMTcWGYGxl6Rs0CXPxnlADumLFO4',
    appId: '1:832200775771:ios:f55c531d76404e3f15477e',
    messagingSenderId: '832200775771',
    projectId: 'icar-2d12c',
    storageBucket: 'icar-2d12c.firebasestorage.app',
    iosBundleId: 'com.example.icarwebview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfeo3194iczUkOiXY6xl8iV6US7_pFg3k',
    appId: '1:832200775771:web:dcae69bb59d0a10715477e',
    messagingSenderId: '832200775771',
    projectId: 'icar-2d12c',
    authDomain: 'icar-2d12c.firebaseapp.com',
    storageBucket: 'icar-2d12c.firebasestorage.app',
    measurementId: 'G-PD792QFSRZ',
  );
}
